### PR TITLE
Create ComponentStateEvent payload

### PR DESCRIPTION
**Pull request by 0xMemoryGrinder**
Solves #109

### CODE REVIEW

**Comment by 0xSwapFeeder** [comment]
Ask for @0xMemoryGrinder 's review if it lgty

**Comment by 0xtekgrinder** [comment]
Why am I assigned ?

**Comment by 0xSwapFeeder** [comment]
> Why am I assigned ?

Because ur requested as reviewer, dumby @0xMemoryGrinder asked me for review but that's my work ^^

**Comment by 0xtekgrinder** [comment]
well assign me reviewer then not only assignee xd

**Review by 0xtekgrinder — APPROVED** [review]
LGTM

**Pull request merged**
