### PR TITLE
Create ReadFileEvent payload

### PR DESCRIPTION
**Pull request by 0xMemoryGrinder**
Solves #96

### CODE REVIEW

**Comment by 0xtekgrinder** [comment]
Moved from the contracts to add only filepath

**Review by 0xSwapFeeder — CHANGES_REQUESTED** [review]
This payload needs to have uninitialized properties to store future file data as raw and encoded.

**Review by 0xSwapFeeder — CHANGES_REQUESTED** [review]
Need a setData to set file data :)

**Review by 0xSwapFeeder — APPROVED** [review]
lgtm 👍

**Pull request merged**
