### PR TITLE
Feature: added payload library

### PR DESCRIPTION
**Pull request by 0xSwapFeeder**
Added the empty payload library to create future payloads.

All branches must be rebased on dev once this is merge.

### CODE REVIEW

**Review by 0xMemoryGrinder — CHANGES_REQUESTED** [review]
You need to tweak the github actions pipeline to ignore the payload library folder in the `collect_dirs` job but otherwise lgtm

**Comment by 0xSwapFeeder** [comment]
> You need to tweak the github actions pipeline to ignore the payload library folder in the `collect_dirs` job but otherwise lgtm

Hmm, isn't it betted to keep this in CI? I could make a global .hpp file for include exporting, this way it will not compile fail.
(That's supposing the collect_dir action is used to fetch cmake folders to further build, ima right ?)

**Comment by 0xMemoryGrinder** [comment]
It cannot be the same pipeline for this subfolder because the pipeline is tailored for a module build and test

**Review by 0xMemoryGrinder — CHANGES_REQUESTED** [review]
Please tweak the github action job `collect_dirs` to exclude payload-library folder

**Review by 0xMemoryGrinder — APPROVED** [review]
Made the change so LGTM now

**Pull request merged**
